--USE [Lyceum]
--GO

--/** Object:  View [dbo].[VW_INT_LYCEUM_RDSTATION]  **/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

--ALTER  VIEW [dbo].[VW_INT_LYCEUM_RDSTATION]
--AS
SELECT	PE.NOME_COMPL
		,PE.NOME_SOCIAL
		,PE.CPF
		,PE.E_MAIL
		,PE.DT_NASC
		,PE.DDD_FONE_CELULAR
		,PE.CELULAR AS FONE_CELULAR
		,PE.SEXO
		,PE.NECESSIDADE_ESPECIAL
		,CA.CANDIDATO 
		,ESTAGIO_CANDIDATO = CASE WHEN CA.CANDIDATO IN (
														SELECT  A.CANDIDATO
														FROM	LY_CANDIDATO A
														JOIN	LY_ALUNO B ON A.CANDIDATO = B.CANDIDATO
																			AND A.CONCURSO = B.CONCURSO
														JOIN	IE_AL_ADIMP_MATRICULA C ON C.ALUNO = B.ALUNO
														where	A.CONCURSO = CA.CONCURSO
														)
									THEN 'PMP'
									WHEN CA.CANDIDATO IN (
														SELECT  A.CANDIDATO
														FROM	LY_CANDIDATO A
														JOIN	LY_ALUNO B ON A.CANDIDATO = B.CANDIDATO
																			AND A.CONCURSO = B.CONCURSO
														where	A.CONCURSO = CA.CONCURSO
														)
									THEN 'PMA'
									WHEN CA.CANDIDATO IN (
														SELECT  A.CANDIDATO
														FROM	LY_CONVOCADOS_VEST A
														WHERE   A.CONCURSO = CA.CONCURSO
														)
									THEN 'CONV'
									ELSE 'INSCRITO'
									END
,PERIODO_LETIVO = CONVERT(VARCHAR, CO.ANO)+'.'+CONVERT(VARCHAR, CO.SEMESTRE)
,Tipo_Curso = CU.TIPO
,Modalidade = DBO.MODALIDADE_NOME(CU.INEP_PRESENCIAL)
,Curso = CU.NOME
,Campus = OC.UNIDADE_FISICA
,Turno = OC.TURNO
,Ingresso = CO.TIPO_CONCURSO
,Nota_ENEM = (
			SELECT CONVERT(FLOAT, AVG(NOTA_BRUTA))
			FROM LY_NOTAS_VEST NV 
			WHERE AREA = 'ENEM' 
			AND NV.CANDIDATO = CA.CANDIDATO 
			AND NV.CONCURSO = CA.CONCURSO
			)
,Nota_Vestibular = (
			SELECT NOTA_BRUTA 
			FROM LY_NOTAS_VEST NV 
			WHERE PROVAVEST = 'REDA��O' 
			AND NV.CANDIDATO = CA.CANDIDATO 
			AND NV.CONCURSO = CA.CONCURSO
			AND CO.TIPO_CONCURSO = 'VestAgend'
			)
,Data_Inscri��o = DT_INSCRICAO
,Data_Convoca��o = (SELECT MAX(DATA) FROM IE_LY_CONVOCADOS_VEST CNV WHERE CNV.CANDIDATO = CA.CANDIDATO AND CNV.CONCURSO = CA.CONCURSO)
,Situa��o = SIT_CANDIDATO_VEST
,Valor_Inscri��o
,Data_Vencimento_Inscri��o = CA.BOL_DT_VENC
,Boleto_Pago_Inscri��o = CA.BOLETO_PAGO
,Data_Pagamento_Inscri��o = CA.BOLETO_DT_PAGAMENTO
,Valor_Matr�cula = (
					SELECT SUM(VALOR)
					FROM LY_COBRANCA A
					JOIN LY_ITEM_LANC B ON A.COBRANCA = B.COBRANCA
					JOIN LY_ALUNO AL ON AL.ALUNO = A.ALUNO
					WHERE A.COBRANCA = (
									 SELECT MIN(COBRANCA)
									 FROM	LY_COBRANCA  AA
									 WHERE	AA.COBRANCA = A.COBRANCA
									 )
					AND AL.CANDIDATO = CA.CANDIDATO
					AND	AL.CONCURSO = CA.CONCURSO
					)
,Data_Vencimento_Matr�cula = (
					SELECT TOP 1 A.DATA_DE_VENCIMENTO
					FROM LY_COBRANCA A
					JOIN LY_ITEM_LANC B ON A.COBRANCA = B.COBRANCA
					JOIN LY_ALUNO AL ON AL.ALUNO = A.ALUNO
					WHERE A.COBRANCA = (
									 SELECT MIN(COBRANCA)
									 FROM	LY_COBRANCA  AA
									 WHERE	AA.COBRANCA = A.COBRANCA
									 )
					AND AL.CANDIDATO = CA.CANDIDATO
					AND	AL.CONCURSO = CA.CONCURSO
					)
,Boleto_Pago_Matr�cula = ''
,Data_do_Recebimento_Matr�cula = ''
,CA.FL_FIELD_04 as uuidrd
FROM	LY_CANDIDATO CA
JOIN	LY_CONCURSO CO ON CO.CONCURSO = CA.CONCURSO
JOIN	LY_PESSOA PE ON CA.PESSOA = PE.PESSOA
JOIN	LY_OPCOES_PROC_SELETIVO OP	ON	OP.CANDIDATO = CA.CANDIDATO
									AND OP.CONCURSO = CA.CONCURSO
									AND	OP.ORDEM = '1'
JOIN	LY_OFERTA_CURSO OC ON OC.OFERTA_DE_CURSO = OP.OFERTA_DE_CURSO
JOIN	LY_CURSO CU ON CU.CURSO = OC.CURSO
--WHERE	CA.CANDIDATO = '2024200015'
GO


