SELECT  A.CURSO, C.NOME, 
		A.NOME_COMPL,  
		C.INEP_NIVEL AS TIPO, 
		A.UNIDADE_FISICA AS POLO,
		A.TURNO,
CASE
	WHEN C.INEP_PRESENCIAL = 'D' THEN 'EAD'
	WHEN C.INEP_PRESENCIAL = 'S' THEN 'SEMIPRESENCIAL'	
ELSE INEP_PRESENCIAL
END MODALIDADE
FROM LY_ALUNO AS A 
LEFT JOIN LY_CURSO AS C ON C.CURSO = A.CURSO
WHERE A.SIT_ALUNO = 'ATIVO'
AND  C.INEP_NIVEL = 'GRADUACAO'
AND C.INEP_PRESENCIAL in ('D', 'S') 
GROUP BY A.CURSO, C.NOME, A.NOME_COMPL, C.TIPO, C.INEP_PRESENCIAL, C.INEP_NIVEL, A.UNIDADE_FISICA, A.TURNO
ORDER BY C.NOME ASC, A.NOME_COMPL ASC, A.CURSO ASC;