SELECT	A.COBRANCA, 
		A.ALUNO, 
		A.CURSO, 
		A.TURNO, 
		I.CURRICULO, 
		A.UNID_FISICA, 
		A.RESP, 
		ANO, 
		MES,
		I.BOLETO AS BOLETO_LANC, 
		PARCELA, 
		I.DATA AS DATA_LANC, 
		I.VALOR AS VALOR_LANC, 
		I.DESCRICAO AS DESCR_LANC, 
		ANO_REF_BOLSA, 
		MES_REF_BOLSA,
		NUM_COBRANCA, 
		DATA_DE_VENCIMENTO, 
		DATA_DE_GERACAO,
		DATA_DE_FATURAMENTO, 
		LOTE, 
		DATA_DE_VENCIMENTO_ORIG, 
		LANC_DEB, 
		CODIGO_LANC, 
		MOTIVO_DECISAO
		--LANC_CRED, 
		--ITEMCRED, 
		--C.VALOR AS VALOR_CRED,
		--C.DESCRICAO AS DESCR_CRED, 
		--C.DATA AS DATA_CRED 
FROM LY_COBRANCA A
	JOIN LY_ITEM_LANC I ON A.COBRANCA = I.COBRANCA
	--JOIN LY_ITEM_CRED C ON A.COBRANCA = C.COBRANCA 
			AND A.ALUNO = I.ALUNO 
			AND A.CURSO = I.CURSO --AND A.CURSO = C.CURSO
			AND A.TURNO = I.TURNO --AND A.TURNO = C.TURNO
			AND A.CURRICULO = I.CURRICULO --AND A.CURRICULO = C.CURRICULO
WHERE ANO = '2024' AND PARCELA = '1'
AND CODIGO_LANC = 'MATRICULA'