--BEGIN TRAN

--USE [Lyceum]
--GO

--CREATE PROCEDURE [dbo].[csvCAMPANHA_DOC_PEND_ALUNO] (

--**		PARAMETROS DE TESTE
--DECLARE

(
			@P_DT_APLICACAO VARCHAR(10),
			@P_ALUNO VARCHAR(10),
			@P_PERIODO_INGRESSO VARCHAR(15),
			@P_TIPO_CURSO VARCHAR(4)	
	)
AS

--** SET TESTE

			--SET @P_DT_APLICACAO = '*'  --'2024-03-05' OK
			--SET @P_ALUNO = '*'--'1312082050' OK
			--SET @P_PERIODO_INGRESSO = '*' --'2013.1' OK
			--SET @P_TIPO_CURSO ='*' --'GRA'  OK

BEGIN 
    
    SELECT A.NOME_COMPL,
		   P.E_MAIL,
		   P.DDD_FONE_CELULAR + P.CELULAR AS CELULAR,
		   C.CANDIDATO,
		   A.ALUNO,
		   CONVERT(VARCHAR, A.ANO_INGRESSO) + '.' + CONVERT(VARCHAR, A.SEM_INGRESSO) AS PERIODO_INGRESSO,
		   CU.TIPO,
		   
						CASE
						WHEN CU.INEP_PRESENCIAL = 'D' THEN 'EAD'
	 					WHEN CU.INEP_PRESENCIAL = 'S' THEN 'SEMIPRESENCIAL'
						WHEN CU.INEP_PRESENCIAL = 'P' THEN 'PRESENCIAL'		
						ELSE CU.INEP_PRESENCIAL
						END MODALIDADE 
		   ,CU.NOME
		   ,A.UNIDADE_FISICA,
		   A.TURNO,
		   A.TIPO_INGRESSO,
		   A.SERIE,
		   D.TURMA,
		   A.SIT_ALUNO,
		   [dbo].[AL_SIT_ACAD](A.ALUNO) AS SIT_ACADEMICA,
						CASE 
						WHEN INA.ALUNO IS NOT NULL THEN  'INADIMPLENTE' ELSE 'ADIMPLENTE' 
						END STATUS_FINANCEIRO

		   ,APLICACAO = (SELECT APLICACAO FROM IE_LY_OPCOES_APP WHERE APLICACAO ='CAMPANHA_DOC_PEND_ALUNO') 
		   ,DT.DT_CIENTE
	 
    FROM LY_ALUNO A
	JOIN LY_CURSO CU ON CU.CURSO = A.CURSO
	JOIN LY_CANDIDATO C ON C.CANDIDATO = A.CANDIDATO
	JOIN LY_PESSOA P ON P.PESSOA = A.PESSOA
	JOIN Aplicacoes.[dbo].[CienteAlunoDoc] DT ON DT.ALUNO = A.ALUNO COLLATE SQL_Latin1_General_CP1_CI_AI
	JOIN LY_MATRICULA D ON D.ALUNO = A.ALUNO 
	LEFT JOIN IE_AL_INADIMPLENTES_NG INA ON INA.ALUNO = A.ALUNO AND Valor_Base > '20' 
			
    WHERE	((CONVERT(VARCHAR, A.ANO_INGRESSO) + '.' + CONVERT(VARCHAR, A.SEM_INGRESSO) = @P_PERIODO_INGRESSO AND @P_PERIODO_INGRESSO <> '*') OR (@P_PERIODO_INGRESSO = '*'))
	AND		((CONVERT(VARCHAR, DT.DT_CIENTE) = @P_DT_APLICACAO AND @P_DT_APLICACAO <> '*' ) OR (@P_DT_APLICACAO = '*'))
	AND		((CONVERT(VARCHAR, A.ALUNO) = @P_ALUNO AND @P_ALUNO <> '*' ) OR (@P_ALUNO = '*'))
	AND		((CONVERT(VARCHAR, CU.TIPO) = @P_TIPO_CURSO AND @P_TIPO_CURSO <> '*' ) OR (@P_TIPO_CURSO = '*'))

--END
--GO

--ROLLBACK
--COMMIT










	